### ISSUE TITLE
How to set NSToolBarItem to the right?

### ISSUE THREAD

**Issue by piaojin** [lukakerr/NSWindowStyles#4]
How to set NSToolBarItem to the right? I cannot find any API to set the position of NSToolBarItem. Please share with me if you have any ideas.  Thank you!

**Comment by lukakerr** [comment]
Use a `flexibleSpace` NSToolBarItem

**Comment by piaojin** [comment]
> Use a `flexibleSpace` NSToolBarItem

@lukakerr Nice. Thank you!
